In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.shape

(2, 4)

In [7]:
arr2[0]

array([1, 2, 3, 4])

In [9]:
arr2[1]

array([5, 6, 7, 8])

In [10]:
arr1.shape

(3,)

In [11]:
arr1

array([1., 2., 3.])

In [12]:
data2 = [[[1, 2,4], [3, 4,5]], [[5, 6,5], [7, 8,11]]]
arr3 = np.array(data2)
arr3.shape

(2, 2, 3)

In [13]:
arr3[0]

array([[1, 2, 4],
       [3, 4, 5]])

In [14]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.dtype)
arr.astype(int)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
float64


array([ 3, -1, -2,  0, 12, 10])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(15)%3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32)

In [23]:
np.arange(15)//3

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int32)

In [25]:
np.arange(15)%7+1

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1], dtype=int32)

In [26]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [27]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [28]:
j=[1.9,2.2,3.3]
int(j[0])

1

In [30]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])


In [31]:
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
1 / arr
arr ** 0.5

C:\Users\xxx.XXX\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


In [37]:
arr2


array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])