In [2]:
import pandas as pd
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                   'A': [1, 2, 3],
                   'B': [4, 5, 6],
                   'C': [7, 8, 9]})
df

A  B  C  key
0  1  4  7  foo
1  2  5  8  bar
2  3  6  9  baz

In [3]:
melted = pd.melt(df, ['key'])
melted

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [4]:
reshaped = melted.pivot('key', 'variable', 'value')
reshaped

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/wesm/pydata-book/2nd-edition/examples/macrodata.csv')

In [8]:
df.dtypes

year        float64
quarter     float64
realgdp     float64
realcons    float64
realinv     float64
realgovt    float64
realdpi     float64
cpi         float64
m1          float64
tbilrate    float64
unemp       float64
pop         float64
infl        float64
realint     float64
dtype: object

In [9]:
df

year  quarter    realgdp  realcons   realinv  realgovt  realdpi  \
0    1959.0      1.0   2710.349    1707.4   286.898   470.045   1886.9   
1    1959.0      2.0   2778.801    1733.7   310.859   481.301   1919.7   
2    1959.0      3.0   2775.488    1751.8   289.226   491.260   1916.4   
3    1959.0      4.0   2785.204    1753.7   299.356   484.052   1931.3   
4    1960.0      1.0   2847.699    1770.5   331.722   462.199   1955.5   
5    1960.0      2.0   2834.390    1792.9   298.152   460.400   1966.1   
6    1960.0      3.0   2839.022    1785.8   296.375   474.676   1967.8   
7    1960.0      4.0   2802.616    1788.2   259.764   476.434   1966.6   
8    1961.0      1.0   2819.264    1787.7   266.405   475.854   1984.5   
9    1961.0      2.0   2872.005    1814.3   286.246   480.328   2014.4   
10   1961.0      3.0   2918.419    1823.1   310.227   493.828   2041.9   
11   1961.0      4.0   2977.830    1859.6   315.463   502.521   2082.0   
12   1962.0      1.0   3031.241    1879.4   334.271   520.960   2101.7   
13   1962.0      2.0   3064.709    1902.5   331.039   523.066   2125.2   
14   1962.0      3.0   3093.047    1917.9   336.962   538.838   2137.0   
15   1962.0      4.0   3100.563    1945.1   325.650   535.912   2154.6   
16   1963.0      1.0   3141.087    1958.2   343.721   522.917   2172.5   
17   1963.0      2.0   3180.447    1976.9   348.730   518.108   2193.1   
18   1963.0      3.0   3240.332    2003.8   360.102   546.893   2217.9   
19   1963.0      4.0   3264.967    2020.6   364.534   532.383   2254.6   
20   1964.0      1.0   3338.246    2060.5   379.523   529.686   2299.6   
21   1964.0      2.0   3376.587    2096.7   377.778   526.175   2362.1   
22   1964.0      3.0   3422.469    2135.2   386.754   522.008   2392.7   
23   1964.0      4.0   3431.957    2141.2   389.910   514.603   2420.4   
24   1965.0      1.0   3516.251    2188.8   429.145   508.006   2447.4   
25   1965.0      2.0   3563.960    2213.0   429.119   508.931   2474.5   
26   1965.0      3.0   3636.285    2251.0   444.444   529.446   2542.6   
27   1965.0      4.0   3724.014    2314.3   446.493   544.121   2594.1   
28   1966.0      1.0   3815.423    2348.5   484.244   556.593   2618.4   
29   1966.0      2.0   3828.124    2354.5   475.408   571.371   2624.7   
..      ...      ...        ...       ...       ...       ...      ...   
173  2002.0      2.0  11538.770    7997.8  1810.779   774.408   8658.9   
174  2002.0      3.0  11596.430    8052.0  1814.531   786.673   8629.2   
175  2002.0      4.0  11598.824    8080.6  1813.219   799.967   8649.6   
176  2003.0      1.0  11645.819    8122.3  1813.141   800.196   8681.3   
177  2003.0      2.0  11738.706    8197.8  1823.698   838.775   8812.5   
178  2003.0      3.0  11935.461    8312.1  1889.883   839.598   8935.4   
179  2003.0      4.0  12042.817    8358.0  1959.783   845.722   8986.4   
180  2004.0      1.0  12127.623    8437.6  1970.015   856.570   9025.9   
181  2004.0      2.0  12213.818    8483.2  2055.580   861.440   9115.0   
182  2004.0      3.0  12303.533    8555.8  2082.231   876.385   9175.9   
183  2004.0      4.0  12410.282    8654.2  2125.152   865.596   9303.4   
184  2005.0      1.0  12534.113    8719.0  2170.299   869.204   9189.6   
185  2005.0      2.0  12587.535    8802.9  2131.468   870.044   9253.0   
186  2005.0      3.0  12683.153    8865.6  2154.949   890.394   9308.0   
187  2005.0      4.0  12748.699    8888.5  2232.193   875.557   9358.7   
188  2006.0      1.0  12915.938    8986.6  2264.721   900.511   9533.8   
189  2006.0      2.0  12962.462    9035.0  2261.247   892.839   9617.3   
190  2006.0      3.0  12965.916    9090.7  2229.636   892.002   9662.5   
191  2006.0      4.0  13060.679    9181.6  2165.966   894.404   9788.8   
192  2007.0      1.0  13099.901    9265.1  2132.609   882.766   9830.2   
193  2007.0      2.0  13203.977    9291.5  2162.214   898.713   9842.7   
194  2007.0      3.0  13321.109    9335.6  2166.491   918.983   9883.9   
195  2007.0

In [2]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

In [5]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})
data
df2 = pd.DataFrame(data.values, columns=['one', 'two', 'three'])
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [6]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [7]:


model_cols = ['x0', 'x1']
data.loc[:, model_cols].values



array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [8]:


data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                  categories=['a', 'b'])
data



x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [9]:
dummies = pd.get_dummies(data.category, prefix='category')
data_with_dummies = data.drop('category', axis=1).join(dummies)
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5           1           0
1   2 -0.01  0.0           0           1
2   3  0.25  3.6           1           0
3   4 -4.10  1.3           1           0
4   5  0.00 -2.0           0           1

In [10]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})
data
import patsy
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [18]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [11]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [13]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [14]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [15]:
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [16]:
coef, resid, _, _ = np.linalg.lstsq(X, y)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


In [17]:
coef

array([[ 0.3129],
       [-0.0791],
       [-0.2655]])

In [19]:
resid

array([19.6379])

In [20]:


train = pd.read_csv('https://raw.githubusercontent.com/wesm/pydata-book/2nd-edition/datasets/titanic/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/wesm/pydata-book/2nd-edition/datasets/titanic/test.csv')
train[:4]



PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [21]:


train.isnull().sum()




PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [23]:
impute_value = train['Age'].median()
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

In [25]:


train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)



In [26]:
predictors = ['Pclass', 'IsFemale', 'Age']
X_train = train[predictors].values
X_test = test[predictors].values
y_train = train['Survived'].values

In [36]:
test[predictors]

Pclass  IsFemale   Age
0         3         0  34.5
1         3         1  47.0
2         2         0  62.0
3         3         0  27.0
4         3         1  22.0
5         3         0  14.0
6         3         1  30.0
7         2         0  26.0
8         3         1  18.0
9         3         0  21.0
..      ...       ...   ...
408       3         1  28.0
409       3         1   3.0
410       3         1  28.0
411       1         1  37.0
412       3         1  28.0
413       3         0  28.0
414       1         1  39.0
415       3         0  38.5
416       3         0  28.0
417       3         0  28.0

[418 rows x 3 columns]

In [30]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [31]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [32]:
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:


y_predict = model.predict(X_test)
y_predict[:10]



array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [35]:
X_test[:10]

array([[ 3. ,  0. , 34.5],
       [ 3. ,  1. , 47. ],
       [ 2. ,  0. , 62. ],
       [ 3. ,  0. , 27. ],
       [ 3. ,  1. , 22. ],
       [ 3. ,  0. , 14. ],
       [ 3. ,  1. , 30. ],
       [ 2. ,  0. , 26. ],
       [ 3. ,  1. , 18. ],
       [ 3. ,  0. , 21. ]])

In [37]:


from sklearn.linear_model import LogisticRegressionCV
model_cv = LogisticRegressionCV(10)
model_cv.fit(X_train, y_train)



LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [38]:
from sklearn.model_selection import cross_val_score
model = LogisticRegression(C=10)
scores = cross_val_score(model, X_train, y_train, cv=4)
scores

array([0.7723, 0.8027, 0.7703, 0.7883])

In [39]:
import statsmodels.api as sm


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [43]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit ([[0, 0], [1, 1], [2, 2],[3,3]], [0, 10, 20,30])
reg.coef_


array([5., 5.])